name: Deploy Java App
runs-on: self-hosted

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and deploy with Docker Compose
        run: |
          docker compose down
          docker compose build --no-cache
          docker compose up -d
